networks:
  default:


services:
  app:
    container_name: app
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./images:/app/images
      - ./logs:/app/logs
    networks:
      - default

  nginx:
    container_name: nginx
    command: nginx -g "daemon off;"
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./images:/images
      - ./logs:/var/log/nginx
      - ./static:/etc/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - default
    depends_on:
      - app
